export const GET_BOOKS = "GET_BOOKS";
export const GET_BOOKS_SUCCEED = "GET_BOOKS_SUCCEED";
export const GET_BOOKS_FAILED = "GET_BOOKS_FAILED";

export const DELETE_BOOK = "DELETE_BOOK";
export const DELETE_BOOK_SUCCEED = "DELETE_BOOK_SUCCEED";
export const DELETE_BOOK_FAILED = "DELETE_BOOK_FAILED";

export const CREATE_BOOK = "CREATE_BOOK";
export const CREATE_BOOK_SUCCEED = "CREATE_BOOK_SUCCEED";
export const CREATE_BOOK_FAILED = "CREATE_BOOK_FAILED";

export const RATE_BOOK = "RATE_BOOK";
export const RATE_BOOK_SUCCEED = "RATE_BOOK_SUCCEED";
export const RATE_BOOK_FAILED = "RATE_BOOK_FAILED";