export const GET_COLLECTIONS = "GET_COLLECTIONS";
export const GET_COLLECTIONS_SUCCEED = "GET_COLLECTIONS_SUCCEED";
export const GET_COLLECTIONS_FAILED = "GET_COLLECTIONS_FAILED";

export const GET_SINGLE_COLLECTION = "GET_SINGLE_COLLECTION";
export const GET_SINGLE_COLLECTION_SUCCEED = "GET_SINGLE_COLLECTION_SUCCEED";
export const GET_SINGLE_COLLECTION_FAILED = "GET_SINGLE_COLLECTION_FAILED";

export const EDIT_SINGLE_COLLECTION = "EDIT_SINGLE_COLLECTION";
export const EDIT_SINGLE_COLLECTION_SUCCEED = "EDIT_SINGLE_COLLECTION_SUCCEED";
export const EDIT_SINGLE_COLLECTION_FAILED = "EDIT_SINGLE_COLLECTION_FAILED";

export const ADD_BOOK = "ADD_BOOK";
export const ADD_BOOK_SUCCEED = "ADD_BOOK_SUCCEED";
export const ADD_BOOK_FAILED = "ADD_BOOK_FAILED";

export const REMOVE_BOOK = "REMOVE_BOOK";
export const REMOVE_BOOK_SUCCEED = "REMOVE_BOOK_SUCCEED";
export const REMOVE_BOOK_FAILED = "REMOVE_BOOK_FAILED";

export const CLEAR_SINGLE_COLLECTION = "CLEAR_SINGLE_COLLECTION";

export const DELETE_COLLECTION = "DELETE_COLLECTION";

export const CREATE_COLLECTION = "CREATE_COLLECTION";
export const CREATE_COLLECTION_SUCCEED = "CREATE_COLLECTION_SUCCEED";
export const CREATE_COLLECTION_FAILED = "CREATE_COLLECTION_FAILED";
