export const GET_COLLECTIONS = "GET_COLLECTIONS";
export const GET_COLLECTIONS_SUCCEED = "GET_COLLECTIONS_SUCCEED";
export const GET_COLLECTIONS_FAILED = "GET_COLLECTIONS_FAILED";

export const GET_SINGLE_COLLECTION = "GET_SINGLE_COLLECTION";
export const GET_SINGLE_COLLECTION_SUCCEED = "GET_SINGLE_COLLECTION_SUCCEED";
export const GET_SINGLE_COLLECTION_FAILED = "GET_SINGLE_COLLECTION_FAILED";

export const EDIT_SINGLE_COLLECTION = "EDIT_SINGLE_COLLECTION";
export const EDIT_SINGLE_COLLECTION_SUCCEED = "EDIT_SINGLE_COLLECTION_SUCCEED";
export const EDIT_SINGLE_COLLECTION_FAILED = "EDIT_SINGLE_COLLECTION_FAILED";